### PR TITLE
Attempt to use new Pulumi bridge for Terraform Plugin Framework

### PR DESCRIPTION
**Pull request by ryanrasti**
Attempt to use the preview Pulumi bridge for the TPF by [following the README](https://github.com/pulumi/pulumi-terraform-bridge/tree/master/pf#readme). I put the Pulumi bridge code directly in main as its much simpler than doing the shim stuff in that README.

As a first pass, I'm just trying to get the code in `main` to compile, but I think there's an issue because doing a `go get github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge` upgrades dependency `terraform-plugin-framework` from v0.11.1 to v1.1.1 and it appears some internal stuff is breaking. I don't have enough knowledge of go or the libraries in question to know if its possible to downgrade or not.

If someone could pick this draft up or give any pointers -- that'd be really helpful!

```
$ go build
# github.com/fly-apps/terraform-provider-fly/internal/provider/modifiers
internal/provider/modifiers/string_default.go:33:70: undefined: tfsdk.ModifyAttributePlanRequest
internal/provider/modifiers/string_default.go:33:110: undefined: tfsdk.ModifyAttributePlanResponse
internal/provider/modifiers/string_default.go:45:10: str.Null undefined (type basetypes.StringValue has no field or method Null)
internal/provider/modifiers/string_default.go:49:36: unknown field 'Value' in struct literal of type basetypes.StringValue
# github.com/fly-apps/terraform-provider-fly/internal/utils
internal/utils/maps.go:10:8: TFMap.ElemType undefined (type basetypes.MapValue has no field or method ElemType)
internal/utils/maps.go:12:12: TFMap.Elems undefined (type basetypes.MapValue has no field or method Elems)
internal/utils/maps.go:13:10: TFMap.Elems undefined (type basetypes.MapValue has no field or method Elems)
internal/utils/maps.go:15:9: TFMap.Elems undefined (type basetypes.MapValue has no field or method Elems)
internal/utils/maps.go:15:35: unknown field 'Value' in struct literal of type basetypes.StringValue
# github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge
../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.1.0/tfbridge/naming.go:33:44: undefined: tfgen.Renames
../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.1.0/tfbridge/provider.go:86:20: undefined: tfgen.Renames
```

### CODE REVIEW

**Comment by cowwoc** [comment]
@DAlperin Any ideas?

**Comment by commandodev** [comment]
Not sure how much help I could be here, but I would love to be able to use pulumi with Fly!

**Comment by remorses** [comment]
`terraform-plugin-framework` has been updated so it should be possible to integrate pulumi now

**Comment by zxaos** [comment]
Looks like this was resolved by #180 so I'm going to close this.

**Comment by cowwoc** [comment]
Does anyone understand how to actually use this? Is there an out-of-the-box fly.io provider or what do end-users have to do to make this work?

**Comment by mootari** [comment]
@zxaos From what I understand (which is very little) the bridge has to be implemented explicitly, so I don't think this PR can be closed just yet?

**Pull request closed without merging**
